In [15]:

input_string = input("Enter the string: ")
char_list = list(input_string)

if len(char_list) >= 2:

    del char_list[0]
    del char_list[0]

    char_list.reverse()

    reversed_string = "".join(char_list)
    print(reversed_string)
else:
    print("The input string is too short to delete 2 characters.")

Enter the string: python
noht

In [ ]:

num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

addition = num1 + num2
subtraction = num1 - num2
multiplication = num1 * num2
division = num1 / num2 if num2 != 0 else "undefined"

print(f"The sum of {num1} and {num2} is: {addition}")
print(f"The difference when {num2} is subtracted from {num1} is: {subtraction}")
print(f"The product of {num1} and {num2} is: {multiplication}")
print(f"The division of {num1} by {num2} is: {division}")

Enter the first number: 10
Enter the second number: 5
The sum of 10.0 and 5.0 is: 15.0
The difference when 5.0 is subtracted from 10.0 is: 5.0
The product of 10.0 and 5.0 is: 50.0
The division of 10.0 by 5.0 is: 2.0

In [ ]:

user_sentence=input(" Enter a sentence:")

def replace_python_with_pythons(sentence):

    modified_sentence = sentence.replace('python', 'pythons')
    return modified_sentence

result = replace_python_with_pythons(user_sentence)
print("Modified sentence:", result)

 Enter a sentence:I love learning python
Modified sentence: I love learning pythons

In [ ]:
def get_letter_grade(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    elif score >= 60:
        return 'D'
    else:
        return 'F'
try:
    user_score = float(input("Enter your class score (0-100): "))

    if 0 <= user_score <= 100

        grade = get_letter_grade(user_score)
        print("Your letter grade is:", grade)
    else:
        print("Invalid score! Please enter a score between 0 and 100.")
except ValueError:
    print("Invalid input! Please enter a numeric score.")

Enter your class score (0-100): 55
Your letter grade is: F

In [ ]:

x = [23, 'Python', 23.98]

types_list = [type(element) for element in x]

print(x)

print(types_list)

[23, 'Python', 23.98]
[<class 'int'>, <class 'str'>, <class 'float'>]

In [ ]:

IT_companies = {'Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle', 'Amazon'}
A = {19, 22, 24, 20, 25, 26}
B = {19, 22, 20, 25, 26, 24, 28, 27}
age = [22, 19, 24, 25, 26, 24, 25, 24]

# 1. Find the length of the set IT_companies
length_IT_companies = len(IT_companies)
print(f"Length of IT_companies: {length_IT_companies}")

# 2. Add 'Twitter' to IT_companies
IT_companies.add('Twitter')
print(f"IT_companies after adding 'Twitter': {IT_companies}")

# 3. Insert multiple IT companies at once to the set IT_companies
new_companies = {'Intel', 'Nvidia', 'Salesforce'}
IT_companies.update(new_companies)
print(f"IT_companies after adding multiple companies: {IT_companies}")

# 4. Remove one of the companies from the set IT_companies
IT_companies.discard('Twitter')  # Using discard to avoid KeyError if the item is not present
print(f"IT_companies after removing 'Twitter': {IT_companies}")

# 5. What is the difference between remove and discard
print("Difference between remove and discard:")
print("- 'remove' raises a KeyError if the element is not present in the set.")
print("- 'discard' does not raise an error if the element is not present in the set.")

# 6. Join A and B
union_AB = A.union(B)
print(f"Union of A and B: {union_AB}")

# 7. Find A intersection B
intersection_AB = A.intersection(B)
print(f"Intersection of A and B: {intersection_AB}")

# 8. Is A subset of B
is_subset = A.issubset(B)
print(f"Is A a subset of B: {is_subset}")

# 9. Are A and B disjoint sets
are_disjoint = A.isdisjoint(B)
print(f"Are A and B disjoint sets: {are_disjoint}")

# 10. Join A with B and B with A
A.update(B)
B.update(A)
print(f"Updated A after joining with B: {A}")
print(f"Updated B after joining with A: {B}")

# 11. What is the symmetric difference between A and B
symmetric_diff_AB = A.symmetric_difference(B)
print(f"Symmetric difference between A and B: {symmetric_diff_AB}")

# 12. Delete the sets completely
del IT_companies
del A
del B

# 13. Convert the ages to a set and compare the length of the list and the set
age_set = set(age)
list_length = len(age)
set_length = len(age_set)
print(f"Length of the list: {list_length}")
print(f"Length of the set: {set_length}")

print(f"Length of the original age list: {list_length}")
print(f"Length of the converted age set: {set_length}")

Length of IT_companies: 7
IT_companies after adding 'Twitter': {'Twitter', 'IBM', 'Oracle', 'Microsoft', 'Apple', 'Facebook', 'Google', 'Amazon'}
IT_companies after adding multiple companies: {'Twitter', 'IBM', 'Nvidia', 'Amazon', 'Salesforce', 'Oracle', 'Intel', 'Apple', 'Facebook', 'Google', 'Microsoft'}
IT_companies after removing 'Twitter': {'IBM', 'Nvidia', 'Amazon', 'Salesforce', 'Oracle', 'Intel', 'Apple', 'Facebook', 'Google', 'Microsoft'}
Difference between remove and discard:
- 'remove' raises a KeyError if the element is not present in the set.
- 'discard' does not raise an error if the element is not present in the set.
Union of A and B: {19, 20, 22, 24, 25, 26, 27, 28}
Intersection of A and B: {19, 20, 22, 24, 25, 26}
Is A a subset of B: True
Are A and B disjoint sets: False
Updated A after joining with B: {19, 20, 22, 24, 25, 26, 27, 28}
Updated B after joining with A: {19, 20, 22, 24, 25, 26, 27, 28}
Symmetric difference between A and B: set()
Length of the list: 8
Length of the set: 5
Length of the original age list: 8
Length of the converted age set: 5